name: pr_to_master

on:
  pull_request:
    branches:
      - master

jobs:
  pr_to_master:
    name:  pr_to_master
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@master
        with:
          python-version: '3.8'

      - name: python basics
        # should prob shift to requirements.txt, but setting like this for now
        run: |
          python3 -m pip install --user pipx
          python3 -m pipx ensurepath
          pipx install meltano

      - name: meltano install
        run: meltano install

      - name: build pipeline
        run: |
          meltano run tap-spreadsheets-anywhere add-timestamps target-duckdb --full-refresh
          meltano invoke dbt-duckdb run-operation elo_rollforward
          meltano run dbt-duckdb:build
